### ISSUE TITLE
Solc 6 introduces a breaking change

### ISSUE THREAD

**Issue by charlescrain** [f-o-a-m/purescript-solc#5]
UPDATE:

Even worse, the downloaded [solcjson downloaded](https://ethereum.github.io/solc-bin/bin/list.json) for 0.6.x acts differently than the solc-js version 0.6.x. 

----

https://github.com/ethereum/solc-js/tree/v0.6.1#high-level-api

Note: 
> It also accepts an optional set of callback functions, which include the import and the smtSolver callbacks. Starting 0.6.0 it only accepts an object in place of the callback to supply the callbacks.

Any attempt to use 0.6.0 causes: 

```
AssertionError [ERR_ASSERTION]: Invalid callback object specified.
```

For Versions after 0.6.x we need to pass in the objects `{import: callBackFunction(filePath)}` rather than just `callBackFunction(filePath)`.

Seems like we should also change:
```
foreign import _compile :: Fn3 SolidityCompiler Json (FilePath -> Effect SolcReadFileCallbackResult) (Effect Json)
```
to:
```
foreign import _compile :: Fn3 SolidityCompiler Json { import :: (FilePath -> Effect SolcReadFileCallbackResult) } (Effect Json)
```
to support the new version going forward.

**Comment by iostat** [comment]
Gonna keep the discussion here rather than chanterelle since this repo is arguably more relevant to the issue assuming its not one of these causes:

* are you using the latest Chanterelle? (`v4.1.0` released two weeks ago was made to fix this very issue, and uses `purescript-solc v1.1.0` released at roughly the same time)
* if you updated a system-wide chanterelle (i.e. `npm install --global chanterelle@4.1.0`), did you run `chanterelle global-postinstall` after doing so? Note that if you're invoking `chanterelle build` to get those errors, you may be using your "old" global chanterelle install which was probably built with 0.5.x
* is the `solc` in your `package.json` `>= 0.6`? v0.6.2 is OpenZeppelin's current minimum solidity version. The solcjs wrapper is... weird. You're almost always better off using a equal or newer `solc` in your `package.json` than your chanterelle.json `solc-version`.
* If you changed the version of `solc`, did you `rm -rf node_modules/solc` before doing `npm install`? npm is... weird.

**Comment by iostat** [comment]
Changed my mind, closing this in favor of the Chanterelle issue, as its more likely a Chanterelle version + paths issue than a purescript-solc issue. 

If you take a peek at https://github.com/f-o-a-m/purescript-solc/blob/v1.1.0/src/Language/Solidity/Compiler.js#L109-L120, you'll see we already do this as of `v1.1.0` I don't imagine we'll be supporting the SAT solver anytime soon until its less experimental.
